import 'package:flutter/material.dart';

class AdaptiveSwitchListTile extends SwitchListTile {
  const AdaptiveSwitchListTile({
    super.key,
    required super.value,
    required super.onChanged,
    super.activeThumbColor,
    super.activeTrackColor,
    super.inactiveThumbColor,
    super.inactiveTrackColor,
    super.activeThumbImage,
    super.onActiveThumbImageError,
    super.inactiveThumbImage,
    super.onInactiveThumbImageError,
    super.thumbColor,
    super.trackColor,
    super.trackOutlineColor,
    super.thumbIcon,
    super.materialTapTargetSize,
    super.dragStartBehavior,
    super.mouseCursor,
    super.overlayColor,
    super.splashRadius,
    super.focusNode,
    super.onFocusChange,
    super.autofocus,
    super.applyCupertinoTheme,
    super.tileColor,
    super.title,
    super.subtitle,
    super.isThreeLine,
    super.dense,
    super.contentPadding,
    super.secondary,
    super.selected,
    super.controlAffinity,
    super.shape,
    super.selectedTileColor,
    super.visualDensity,
    super.enableFeedback,
    super.hoverColor,
    super.internalAddSemanticForOnTap,
  }) : super.adaptive();
}
